# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transaction.proto',
  package='Manufacturing',
  syntax='proto3',
  serialized_pb=_b('\n\x11transaction.proto\x12\rManufacturing\"\xf6\x07\n\x07Payload\x12-\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1d.Manufacturing.Payload.Action\x12\x36\n\x0euserEnrollment\x18\x02 \x01(\x0b\x32\x1e.Manufacturing.Payload.Account\x12\x39\n\x0c\x66\x61\x63toryAsset\x18\x03 \x01(\x0b\x32#.Manufacturing.Payload.FactoryAsset\x12?\n\x0f\x63hangeOwnership\x18\x04 \x01(\x0b\x32&.Manufacturing.Payload.ChangeOwnership\x12-\n\x03\x63\x61r\x18\x05 \x01(\x0b\x32 .Manufacturing.Payload.CreateCar\x1aw\n\x07\x41\x63\x63ount\x12\x18\n\x10organizationName\x18\x01 \x01(\t\x12\r\n\x05orgId\x18\x02 \x01(\t\x12,\n\x04type\x18\x03 \x01(\x0e\x32\x1e.Manufacturing.Payload.OrgType\x12\x15\n\raccountNumber\x18\x04 \x01(\t\x1aO\n\x0c\x46\x61\x63toryAsset\x12\x0f\n\x07\x61ssetId\x18\x01 \x01(\t\x12.\n\x04type\x18\x02 \x01(\x0e\x32 .Manufacturing.Payload.AssetType\x1a\xa1\x01\n\x0f\x43hangeOwnership\x12\x0f\n\x07\x61ssetId\x18\x01 \x01(\t\x12.\n\x04type\x18\x02 \x01(\x0e\x32 .Manufacturing.Payload.AssetType\x12\x17\n\x0fnewOwnerAddress\x18\x03 \x01(\t\x12\x34\n\x0c\x61ssignToType\x18\x04 \x01(\x0e\x32\x1e.Manufacturing.Payload.OrgType\x1ao\n\tCreateCar\x12\x0f\n\x07\x61ssetId\x18\x03 \x01(\t\x12\x0f\n\x07wheelId\x18\x04 \x01(\t\x12\x10\n\x08\x65ngineId\x18\x05 \x01(\t\x12\x17\n\x0ftransmissionsId\x18\x06 \x01(\t\x12\x15\n\rdealerAddress\x18\x07 \x01(\t\"F\n\x06\x41\x63tion\x12\x0b\n\x07\x41\x43\x43OUNT\x10\x00\x12\x10\n\x0c\x43REATE_PARTS\x10\x01\x12\r\n\tOWNERSHIP\x10\x02\x12\x0e\n\nCREATE_CAR\x10\x03\"I\n\tAssetType\x12\x08\n\x04VOID\x10\x00\x12\n\n\x06WHEELS\x10\x01\x12\n\n\x06\x45NGINE\x10\x02\x12\x11\n\rTRANSMISSIONS\x10\x03\x12\x07\n\x03\x43\x41R\x10\x04\"g\n\x07OrgType\x12\x11\n\rORG_TYPE_VOID\x10\x00\x12\x1a\n\x16ORG_TYPE_PARTS_FACTORY\x10\x01\x12\x18\n\x14ORG_TYPE_CAR_FACTORY\x10\x02\x12\x13\n\x0fORG_TYPE_DEALER\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PAYLOAD_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='Manufacturing.Payload.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCOUNT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_PARTS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OWNERSHIP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_CAR', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=801,
  serialized_end=871,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_ACTION)

_PAYLOAD_ASSETTYPE = _descriptor.EnumDescriptor(
  name='AssetType',
  full_name='Manufacturing.Payload.AssetType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VOID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHEELS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENGINE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSMISSIONS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAR', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=873,
  serialized_end=946,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_ASSETTYPE)

_PAYLOAD_ORGTYPE = _descriptor.EnumDescriptor(
  name='OrgType',
  full_name='Manufacturing.Payload.OrgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ORG_TYPE_VOID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORG_TYPE_PARTS_FACTORY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORG_TYPE_CAR_FACTORY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORG_TYPE_DEALER', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=948,
  serialized_end=1051,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_ORGTYPE)


_PAYLOAD_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='Manufacturing.Payload.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizationName', full_name='Manufacturing.Payload.Account.organizationName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orgId', full_name='Manufacturing.Payload.Account.orgId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Manufacturing.Payload.Account.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accountNumber', full_name='Manufacturing.Payload.Account.accountNumber', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=441,
)

_PAYLOAD_FACTORYASSET = _descriptor.Descriptor(
  name='FactoryAsset',
  full_name='Manufacturing.Payload.FactoryAsset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assetId', full_name='Manufacturing.Payload.FactoryAsset.assetId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Manufacturing.Payload.FactoryAsset.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=522,
)

_PAYLOAD_CHANGEOWNERSHIP = _descriptor.Descriptor(
  name='ChangeOwnership',
  full_name='Manufacturing.Payload.ChangeOwnership',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assetId', full_name='Manufacturing.Payload.ChangeOwnership.assetId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Manufacturing.Payload.ChangeOwnership.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newOwnerAddress', full_name='Manufacturing.Payload.ChangeOwnership.newOwnerAddress', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='assignToType', full_name='Manufacturing.Payload.ChangeOwnership.assignToType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=686,
)

_PAYLOAD_CREATECAR = _descriptor.Descriptor(
  name='CreateCar',
  full_name='Manufacturing.Payload.CreateCar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assetId', full_name='Manufacturing.Payload.CreateCar.assetId', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wheelId', full_name='Manufacturing.Payload.CreateCar.wheelId', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='engineId', full_name='Manufacturing.Payload.CreateCar.engineId', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transmissionsId', full_name='Manufacturing.Payload.CreateCar.transmissionsId', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dealerAddress', full_name='Manufacturing.Payload.CreateCar.dealerAddress', index=4,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=799,
)

_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='Manufacturing.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='Manufacturing.Payload.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userEnrollment', full_name='Manufacturing.Payload.userEnrollment', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factoryAsset', full_name='Manufacturing.Payload.factoryAsset', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='changeOwnership', full_name='Manufacturing.Payload.changeOwnership', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='car', full_name='Manufacturing.Payload.car', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PAYLOAD_ACCOUNT, _PAYLOAD_FACTORYASSET, _PAYLOAD_CHANGEOWNERSHIP, _PAYLOAD_CREATECAR, ],
  enum_types=[
    _PAYLOAD_ACTION,
    _PAYLOAD_ASSETTYPE,
    _PAYLOAD_ORGTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=1051,
)

_PAYLOAD_ACCOUNT.fields_by_name['type'].enum_type = _PAYLOAD_ORGTYPE
_PAYLOAD_ACCOUNT.containing_type = _PAYLOAD
_PAYLOAD_FACTORYASSET.fields_by_name['type'].enum_type = _PAYLOAD_ASSETTYPE
_PAYLOAD_FACTORYASSET.containing_type = _PAYLOAD
_PAYLOAD_CHANGEOWNERSHIP.fields_by_name['type'].enum_type = _PAYLOAD_ASSETTYPE
_PAYLOAD_CHANGEOWNERSHIP.fields_by_name['assignToType'].enum_type = _PAYLOAD_ORGTYPE
_PAYLOAD_CHANGEOWNERSHIP.containing_type = _PAYLOAD
_PAYLOAD_CREATECAR.containing_type = _PAYLOAD
_PAYLOAD.fields_by_name['action'].enum_type = _PAYLOAD_ACTION
_PAYLOAD.fields_by_name['userEnrollment'].message_type = _PAYLOAD_ACCOUNT
_PAYLOAD.fields_by_name['factoryAsset'].message_type = _PAYLOAD_FACTORYASSET
_PAYLOAD.fields_by_name['changeOwnership'].message_type = _PAYLOAD_CHANGEOWNERSHIP
_PAYLOAD.fields_by_name['car'].message_type = _PAYLOAD_CREATECAR
_PAYLOAD_ACTION.containing_type = _PAYLOAD
_PAYLOAD_ASSETTYPE.containing_type = _PAYLOAD
_PAYLOAD_ORGTYPE.containing_type = _PAYLOAD
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(

  Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), dict(
    DESCRIPTOR = _PAYLOAD_ACCOUNT,
    __module__ = 'transaction_pb2'
    # @@protoc_insertion_point(class_scope:Manufacturing.Payload.Account)
    ))
  ,

  FactoryAsset = _reflection.GeneratedProtocolMessageType('FactoryAsset', (_message.Message,), dict(
    DESCRIPTOR = _PAYLOAD_FACTORYASSET,
    __module__ = 'transaction_pb2'
    # @@protoc_insertion_point(class_scope:Manufacturing.Payload.FactoryAsset)
    ))
  ,

  ChangeOwnership = _reflection.GeneratedProtocolMessageType('ChangeOwnership', (_message.Message,), dict(
    DESCRIPTOR = _PAYLOAD_CHANGEOWNERSHIP,
    __module__ = 'transaction_pb2'
    # @@protoc_insertion_point(class_scope:Manufacturing.Payload.ChangeOwnership)
    ))
  ,

  CreateCar = _reflection.GeneratedProtocolMessageType('CreateCar', (_message.Message,), dict(
    DESCRIPTOR = _PAYLOAD_CREATECAR,
    __module__ = 'transaction_pb2'
    # @@protoc_insertion_point(class_scope:Manufacturing.Payload.CreateCar)
    ))
  ,
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'transaction_pb2'
  # @@protoc_insertion_point(class_scope:Manufacturing.Payload)
  ))
_sym_db.RegisterMessage(Payload)
_sym_db.RegisterMessage(Payload.Account)
_sym_db.RegisterMessage(Payload.FactoryAsset)
_sym_db.RegisterMessage(Payload.ChangeOwnership)
_sym_db.RegisterMessage(Payload.CreateCar)


# @@protoc_insertion_point(module_scope)
